'use client';

import * as React from 'react';
import { MoreHorizontal, FileText, Download, Check, AlertCircle, RefreshCw, FileCode2, ChevronDown } from 'lucide-react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/src/components/ui/table';
import { Checkbox } from '@/src/components/ui/checkbox';
import { Button } from '@/src/components/ui/button';
import { Badge } from '@/src/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator
} from '@/src/components/ui/dropdown-menu';
import { ExportStatusBadge } from './ExportStatusBadge';
import { ExportPackage } from '../types';
import { cn } from '@/lib/utils';
import { useSidebar } from '@/src/components/shell/SidebarContext';

interface ExportPackagesTableProps {
  packages: ExportPackage[];
  onRetry: (id: string) => void;
  permissionDenied?: boolean;
  selectedIds: string[];
  onSelectToggle: (id: string) => void;
  onSelectAllToggle: (allSelected: boolean) => void;
}

export function ExportPackagesTable({
  packages,
  onRetry,
  permissionDenied = false,
  selectedIds,
  onSelectToggle,
  onSelectAllToggle
}: ExportPackagesTableProps) {
  const { isCollapsed } = useSidebar();
  const [downloadSuccessId, setDownloadSuccessId] = React.useState<string | null>(null);
  const [openModalId, setOpenModalId] = React.useState<string | null>(null);

  const areAllSelected = packages.length > 0 && selectedIds.length === packages.length;

  const handleSelectAllChange = (checked: boolean) => {
    onSelectAllToggle(checked);
  };

  const handleDownloadClick = (pkgId: string, format: string) => {
    // Simulate a successful download
    setDownloadSuccessId(pkgId);
    setTimeout(() => setDownloadSuccessId(null), 2500);
  };

  const handleOpenClick = (pkgName: string) => {
    alert(`[Prototype Note] Opening assessments workbench details for: ${pkgName}`);
  };

  const getMarketFlag = (market: 'US' | 'EU' | 'JP') => {
    switch (market) {
      case 'US': return '🇺🇸';
      case 'EU': return '🇪🇺';
      case 'JP': return '🇯🇵';
      default: return '🌐';
    }
  };

  return (
    <div className="space-y-4 select-none">
      {/* 1. DESKTOP VIEW: High-density data table (hidden on lg and smaller screen views) */}
      <div className="hidden lg:block bg-white border border-border rounded-card shadow-sm overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-bg-page/70 border-b border-border">
              <TableHead className="w-[45px] pl-4">
                <Checkbox
                  checked={areAllSelected}
                  onCheckedChange={handleSelectAllChange}
                  disabled={permissionDenied || packages.length === 0}
                />
              </TableHead>
              <TableHead className="min-w-[280px]">Export Package</TableHead>
              <TableHead>Assessment</TableHead>
              <TableHead>Product</TableHead>
              <TableHead>Market</TableHead>
              <TableHead>Patent / Claim</TableHead>
              <TableHead className="min-w-[180px]">Formats / Included Files</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead className="min-w-[140px]">Generated At</TableHead>
              <TableHead className="min-w-[140px]">Last Downloaded</TableHead>
              {!permissionDenied && <TableHead className="text-right pr-4">Actions</TableHead>}
            </TableRow>
          </TableHeader>
          
          <TableBody>
            {packages.map((pkg) => {
              const isSelected = selectedIds.includes(pkg.id);

              return (
                <TableRow
                  key={pkg.id}
                  data-state={isSelected ? "selected" : undefined}
                  className={cn(
                    "hover:bg-bg-page/50 border-b border-border transition-standard",
                    isSelected && "bg-brand/5 hover:bg-brand/10"
                  )}
                >
                  {/* Checkbox column */}
                  <TableCell className="pl-4">
                    <Checkbox
                      checked={isSelected}
                      onCheckedChange={() => onSelectToggle(pkg.id)}
                      disabled={permissionDenied}
                    />
                  </TableCell>

                  {/* Package Name & ID */}
                  <TableCell className="py-3">
                    <div className="flex gap-3 items-start max-w-sm">
                      {/* Compact File Indicator Widget */}
                      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-control border border-border bg-bg-page text-text-secondary">
                        <FileCode2 className={cn("h-4.5 w-4.5", 
                          pkg.status === 'Ready for Download' ? 'text-brand' : 
                          pkg.status === 'Failed' ? 'text-error' : 'text-warning animate-pulse'
                        )} />
                      </div>
                      <div className="flex flex-col min-w-0">
                        <span className="text-t5 font-bold text-text-primary truncate block hover:text-brand transition-standard cursor-pointer" title={pkg.name}>
                          {pkg.name}
                        </span>
                        <span className="text-t7 text-text-tertiary select-all mt-0.5" style={{ letterSpacing: '0.02em' }}>
                          ID: {pkg.id}
                        </span>
                      </div>
                    </div>
                  </TableCell>

                  {/* Assessment details */}
                  <TableCell className="py-3">
                    <div className="flex flex-col min-w-[110px]">
                      <span className="text-t5 font-semibold text-text-primary">{pkg.assessmentName}</span>
                      <span className="text-t6 text-text-tertiary mt-0.5">{pkg.assessmentCode}</span>
                    </div>
                  </TableCell>

                  {/* Product details */}
                  <TableCell className="py-3">
                    <div className="flex flex-col min-w-[90px]">
                      <span className="text-t5 font-semibold text-text-primary">{pkg.productName}</span>
                      <span className="text-t6 text-text-tertiary mt-0.5">{pkg.productCode}</span>
                    </div>
                  </TableCell>

                  {/* Market Code */}
                  <TableCell className="py-3 select-none">
                    <div className="flex items-center gap-2">
                      <span className="text-base leading-none">{getMarketFlag(pkg.market)}</span>
                      <span className="text-t5 font-semibold text-text-primary uppercase">{pkg.market}</span>
                    </div>
                  </TableCell>

                  {/* Patent Number / Claims */}
                  <TableCell className="py-3">
                    <div className="flex flex-col min-w-[124px]">
                      <span className="text-t5 font-bold text-text-primary block truncate select-all">{pkg.patent}</span>
                      <span className="text-t6 text-text-secondary mt-0.5">{pkg.claim}</span>
                    </div>
                  </TableCell>

                  {/* Formats Badges */}
                  <TableCell className="py-3">
                    <div className="flex flex-wrap items-center gap-1.5 max-w-[200px]">
                      {pkg.formats.map((f) => {
                        let color = "bg-blue-100/40 text-blue-800 border-blue-200/50";
                        if (f === 'Excel') color = "bg-green-100/40 text-green-800 border-green-200/50";
                        if (f === 'PDF') color = "bg-red-100/40 text-red-800 border-red-200/50";
                        if (f === 'Evidence') color = "bg-purple-100/40 text-purple-800 border-purple-200/50";
                        
                        return (
                          <Badge key={f} variant="outline" className={cn("px-1.5 py-0.5 text-t7 font-bold", color)}>
                            {f}
                          </Badge>
                        );
                      })}
                      {pkg.formats.includes('PDF') ? (
                        <span className="text-t6 font-semibold text-text-tertiary select-none pl-1">+1</span>
                      ) : null}
                    </div>
                  </TableCell>

                  {/* Status Column */}
                  <TableCell className="py-3">
                    <ExportStatusBadge status={pkg.status} />
                  </TableCell>

                  {/* Generated By */}
                  <TableCell className="py-3">
                    <span className="text-t5 font-semibold text-text-primary whitespace-nowrap">{pkg.generatedBy}</span>
                  </TableCell>

                  {/* Generated At */}
                  <TableCell className="py-3 text-text-secondary">
                    <div className="flex flex-col text-t6 min-w-[110px]">
                      <span className="font-semibold text-text-primary">
                        {pkg.generatedAt.split(' ').slice(0, 3).join(' ')}
                      </span>
                      <span className="text-text-tertiary mt-0.5">
                        {pkg.generatedAt.split(' ').slice(3).join(' ')}
                      </span>
                    </div>
                  </TableCell>

                  {/* Last Downloaded */}
                  <TableCell className="py-3 text-text-secondary">
                    {pkg.lastDownloaded ? (
                      <div className="flex flex-col text-t6 min-w-[110px]">
                        <span className="font-semibold text-text-primary">
                          {pkg.lastDownloaded.split(' ').slice(0, 3).join(' ')}
                        </span>
                        <span className="text-text-tertiary mt-0.5">
                          {pkg.lastDownloaded.split(' ').slice(3).join(' ')}
                        </span>
                      </div>
                    ) : (
                      <span className="text-t5 text-text-tertiary font-semibold pl-2">—</span>
                    )}
                  </TableCell>

                  {/* Actions column (Only shown if NOT permissionDenied) */}
                  {!permissionDenied && (
                    <TableCell className="py-3 text-right pr-4">
                      <div className="flex items-center justify-end gap-1.5 select-none">
                        {pkg.status === 'Ready for Download' && (
                          <>
                            {/* Download Dropdown */}
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="outline" size="sm" className="h-8 text-t6 border-brand/20 text-brand hover:border-brand hover:bg-brand/5 cursor-pointer">
                                  <span>Download</span>
                                  <ChevronDown className="h-3.5 w-3.5 opacity-70 shrink-0" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="right" className="w-[190px]">
                                <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Word')}>
                                  📄 Word Document (.docx)
                                </DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Excel')}>
                                  📊 Excel Worksheets (.xlsx)
                                </DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Evidence')}>
                                  📦 Evidence Source Files (.zip)
                                </DropdownMenuItem>
                                <DropdownMenuSeparator />
                                <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'All')}>
                                  🗂️ Entire ZIP Deliverable
                                </DropdownMenuItem>
                              </DropdownMenuContent>
                            </DropdownMenu>

                            {/* Open Dropdown */}
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="ghost" size="sm" className="h-8 text-t6 hover:bg-slate-100 cursor-pointer">
                                  <span>Open</span>
                                  <ChevronDown className="h-3.5 w-3.5 opacity-70 shrink-0" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="right" className="w-52">
                                <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                  🔍 View Assessments Audit Ledger
                                </DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                  📑 Edit Claim Chart Evidence Mapping
                                </DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                  ⚖️ Open Legal Attorney Workbench
                                </DropdownMenuItem>
                              </DropdownMenuContent>
                            </DropdownMenu>
                          </>
                        )}

                        {pkg.status === 'Generating' && (
                          <>
                            <Button
                              variant="outline"
                              size="sm"
                              className="h-8 text-t6 text-text-secondary border-border"
                              onClick={() => alert(`Generating: Background synthesis task ${pkg.id} is at 45% completion. Current worker stage: LLM Claim Chart parsing.`)}
                            >
                              <span>View Progress</span>
                            </Button>
                            <Button variant="outline" size="sm" className="h-8 text-t6 opacity-50 cursor-not-allowed" disabled>
                              <span>Download</span>
                            </Button>
                          </>
                        )}

                        {pkg.status === 'Failed' && (
                          <>
                            <Button
                              variant="outline"
                              size="sm"
                              className="h-8 text-t6 border-red-200 text-error hover:bg-red-50/20"
                              onClick={() => onRetry(pkg.id)}
                            >
                              <RefreshCw className="h-3 w-3 shrink-0 animate-spin-reverse-once" />
                              <span>Retry Export</span>
                            </Button>
                            
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="ghost" size="sm" className="h-8 text-t6 hover:bg-slate-100 cursor-pointer">
                                  <span>Open</span>
                                  <ChevronDown className="h-3.5 w-3.5 opacity-70 shrink-0" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="right">
                                <DropdownMenuItem onClick={() => alert("Reviewing Failure Logs: LLM parser encountered layout exception in US-PACK-017 PDF file.")}>
                                  ⚠️ Inspect Error Log
                                </DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                  📑 Edit Source Mapping
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </>
                )}

                        {/* More Menu */}
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" className="h-8 w-8 text-text-secondary hover:bg-slate-100 cursor-pointer">
                              <MoreHorizontal className="h-4.5 w-4.5" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="right" className="w-44">
                            <DropdownMenuItem className="text-text-primary">
                              📝 Rename Package
                            </DropdownMenuItem>
                            <DropdownMenuItem className="text-text-primary">
                              🔒 Lock Deliverable
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem className="text-error hover:bg-error-bg">
                              🗑️ Delete / Archive
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                    </TableCell>
                  )}
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>

      {/* 2. TABLET/MOBILE VIEW: Lightweight adaptive cards (renders on lg-screens and smaller) */}
      <div className="lg:hidden space-y-4">
        {/* Mobile Select All Header bar */}
        <div className="bg-white border border-border rounded-card p-3.5 flex items-center justify-between shadow-sm">
          <div className="flex items-center gap-2.5">
            <Checkbox
              checked={areAllSelected}
              onCheckedChange={handleSelectAllChange}
              disabled={permissionDenied || packages.length === 0}
            />
            <span className="text-text-primary text-t5 font-bold">Select All Available ({packages.length})</span>
          </div>
          {selectedIds.length > 0 && (
            <span className="text-t6 font-semibold bg-brand/10 text-brand px-2.5 py-0.5 rounded-full">
              {selectedIds.length} Selected
            </span>
          )}
        </div>

        {/* Card Stack Grid */}
        <div className={cn(
          "grid grid-cols-1 gap-4",
          isCollapsed ? "sm:grid-cols-2" : "sm:grid-cols-2 md:grid-cols-1"
        )}>
          {packages.map((pkg) => {
            const isSelected = selectedIds.includes(pkg.id);
            return (
              <div
                key={pkg.id}
                className={cn(
                  "bg-white border rounded-card p-4 shadow-sm transition-standard flex flex-col gap-3.5",
                  isSelected ? "border-brand bg-brand/[0.02]" : "border-border hover:border-border-strong"
                )}
              >
                {/* Header detail */}
                <div className="flex items-start justify-between gap-3 border-b border-divider pb-3">
                  <div className="flex items-start gap-2.5 min-w-0">
                    <div className="pt-0.5">
                      <Checkbox
                        checked={isSelected}
                        onCheckedChange={() => onSelectToggle(pkg.id)}
                        disabled={permissionDenied}
                      />
                    </div>
                    <div className="min-w-0">
                      <span className="text-t7 font-mono text-text-tertiary select-all block leading-none">
                        #{pkg.id.slice(-6).toUpperCase()}
                      </span>
                      <h4 
                        onClick={() => handleOpenClick(pkg.name)}
                        className="text-t4 font-bold text-text-primary mt-1 truncate hover:text-brand cursor-pointer transition-colors"
                        title={pkg.name}
                      >
                        {pkg.name}
                      </h4>
                    </div>
                  </div>
                  <div className="shrink-0">
                    <ExportStatusBadge status={pkg.status} />
                  </div>
                </div>

                {/* Body Meta Grid */}
                <div className="grid grid-cols-2 gap-x-3 gap-y-3.5 text-t6">
                  {/* Assessment Block */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Assessment
                    </span>
                    <span className="font-semibold text-text-primary block truncate">
                      {pkg.assessmentName}
                    </span>
                    <span className="text-text-tertiary text-t7 block truncate mt-0.5">
                      {pkg.assessmentCode}
                    </span>
                  </div>

                  {/* Product Block */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Product
                    </span>
                    <span className="font-semibold text-text-primary block truncate">
                      {pkg.productName}
                    </span>
                    <span className="text-text-tertiary text-t7 block truncate mt-0.5">
                      {pkg.productCode}
                    </span>
                  </div>

                  {/* Market info */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Market
                    </span>
                    <div className="flex items-center gap-1.5 mt-1 select-none">
                      <span className="text-base leading-none">{getMarketFlag(pkg.market)}</span>
                      <span className="font-bold text-text-primary uppercase text-t5">{pkg.market}</span>
                    </div>
                  </div>

                  {/* Patent info */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Patent/Claim
                    </span>
                    <span className="font-bold text-text-primary block truncate select-all">
                      {pkg.patent}
                    </span>
                    <span className="text-text-secondary text-t6 block truncate mt-0.5">
                      {pkg.claim}
                    </span>
                  </div>

                  {/* Included formats */}
                  <div className="min-w-0 col-span-2">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-1.5 select-none">
                      Included Workpaper Formats
                    </span>
                    <div className="flex flex-wrap items-center gap-1.5">
                      {pkg.formats.map((f) => {
                        let color = "bg-blue-100/40 text-blue-800 border-blue-200/50";
                        if (f === 'Excel') color = "bg-green-100/40 text-green-800 border-green-200/50";
                        if (f === 'PDF') color = "bg-red-100/40 text-red-800 border-red-200/50";
                        if (f === 'Evidence') color = "bg-purple-100/40 text-purple-800 border-purple-200/50";
                        
                        return (
                          <Badge key={f} variant="outline" className={cn("px-1.5 py-0.5 text-t7 font-bold", color)}>
                            {f}
                          </Badge>
                        );
                      })}
                    </div>
                  </div>

                  {/* Generated details */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Author
                    </span>
                    <span className="font-semibold text-text-primary block truncate">
                      {pkg.generatedBy}
                    </span>
                  </div>

                  {/* Generation date */}
                  <div className="min-w-0">
                    <span className="text-text-tertiary font-semibold uppercase tracking-wider block mb-0.5 select-none">
                      Last Action
                    </span>
                    <span className="text-text-primary font-semibold block truncate">
                      {pkg.lastDownloaded ? "Downloaded" : "Generated"}
                    </span>
                  </div>
                </div>

                {/* Actions bottom alignment */}
                {!permissionDenied && (
                  <div className="border-t border-divider pt-3.5 flex items-center justify-between gap-3 mt-1.5">
                    <div className="flex flex-wrap items-center gap-1.5">
                      {pkg.status === 'Ready for Download' && (
                        <>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="outline" size="sm" className="h-8 text-t6 border-brand/20 text-brand hover:border-brand hover:bg-brand/5 cursor-pointer">
                                <span>Download</span>
                                <ChevronDown className="h-3.5 w-3.5 opacity-70 shrink-0" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="left" className="w-48">
                              <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Word')}>
                                📄 Word Document (.docx)
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Excel')}>
                                📊 Excel Worksheets (.xlsx)
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'Evidence')}>
                                📦 Evidence Source Files (.zip)
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem onClick={() => handleDownloadClick(pkg.id, 'All')}>
                                🗂️ Entire ZIP Deliverable
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>

                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="sm" className="h-8 text-t6 hover:bg-slate-100 cursor-pointer">
                                <span>Open</span>
                                <ChevronDown className="h-3.5 w-3.5 opacity-70 shrink-0" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="left" className="w-52">
                              <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                🔍 View Assessments Audit Ledger
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                📑 Edit Claim Chart Evidence Mapping
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleOpenClick(pkg.name)}>
                                ⚖️ Open Legal Attorney Workbench
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </>
                      )}

                      {pkg.status === 'Generating' && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 text-t6 text-text-secondary border-border"
                          onClick={() => alert(`Generating task: ${pkg.id} at 45%.`)}
                        >
                          <span>Review Progress</span>
                        </Button>
                      )}

                      {pkg.status === 'Failed' && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 text-t6 border-red-200 text-error hover:bg-red-50/20"
                          onClick={() => onRetry(pkg.id)}
                        >
                          <RefreshCw className="h-3 w-3 shrink-0 mr-1 animate-spin-reverse-once" />
                          <span>Retry Export</span>
                        </Button>
                      )}
                    </div>

                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-text-secondary hover:bg-slate-100 cursor-pointer">
                          <MoreHorizontal className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="right" className="w-44">
                        <DropdownMenuItem className="text-text-primary">
                          📝 Rename Package
                        </DropdownMenuItem>
                        <DropdownMenuItem className="text-text-primary">
                          🔒 Lock Deliverable
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem className="text-error hover:bg-error-bg">
                          🗑️ Delete / Archive
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Shared bottom notification for simulated downloads (works for both table and cards) */}
      {downloadSuccessId && (
        <div className="bg-success-bg border border-success-border rounded-control px-4 py-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 text-t6 text-success animate-in fade-in slide-in-from-bottom-2 mt-2">
          <div className="flex items-start sm:items-center gap-2 font-medium min-w-0">
            <Check className="h-4 w-4 text-success shrink-0 mt-0.5 sm:mt-0" />
            <span className="break-words">Simulated Download Activated: File content compiled successfully and downloaded in background!</span>
          </div>
          <span className="font-mono text-t7 text-text-tertiary hidden sm:inline shrink-0">sec-level packaging</span>
        </div>
      )}
    </div>
  );
}
